version: "3"

services:
  jupyter:
    image: quay.io/jupyter/pyspark-notebook:spark-3.5.0
    ports:
      - 8888:8888
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=sparkpw
    networks:
      - sparknet
    volumes:
      - ./work:/home/jovyan/work
  master:
    image: spark:3.5.0
    hostname: master
    ports:
      - 7077:7077
      - 8080:8080
    networks:
      - sparknet
    entrypoint: [
      "/opt/spark/bin/spark-class", 
      "org.apache.spark.deploy.master.Master"
      ]
  worker:
    image: spark:3.5.0
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - master
    networks:
      - sparknet
    entrypoint: [
      "/opt/spark/bin/spark-class", 
      "org.apache.spark.deploy.worker.Worker", 
      "spark://master:7077"
      ]

  

  minio:
    image: minio/minio:RELEASE.2023-02-10T18-48-39Z
    hostname: minio
    command: server /data --console-address ":9001"
    ports:
    - "9000:9000"
    - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopass
    networks:
      - sparknet    
    volumes:
      - minio-data:/data 

##### networks #####
networks:
  sparknet:
    name: spark-network
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.11.0/24
          gateway: 10.10.11.1

##### Volumes #####
volumes:
  minio-data:
    driver: local